// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpgyhplbwbcyalqeuivx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwZ3locGxid2JjeWFscWV1aXZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NjA4OTMsImV4cCI6MjA2NDAzNjg5M30.jJJFSN4c-PXeeTry3GAGPcwuHrlbjqDzhxi3pf3UgK4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);